### PR TITLE
Fix some minor things

### LINKED ISSUE #548: Bump copyright year to 2017

### PR DESCRIPTION
**Pull request by jdinan**
* Fix issues reported by coverity.
* Close #548

### CODE REVIEW

File: src/transport_ofi.c [hunk 1]
```diff
@@ -95,6 +95,7 @@ static shmem_transport_ctx_t** shmem_transport_ofi_contexts = NULL;
 static size_t shmem_transport_ofi_contexts_len = 0;
 static size_t shmem_transport_ofi_grow_size = 128;
 
+#define SHMEM_CTX_DEFAULT_ID -1
```
Comment (davidozog) [inline src/transport_ofi.c]: Don't we get this from `shmem.h`?

Comment (jdinan) [reply src/transport_ofi.c]: Moved it from shmem.h to transport_ofi.c in e85e895.  Shouldn't need to expose this to users.

Comment (davidozog) [reply src/transport_ofi.c]: Whoops!  I see it's moved.  Good plan.
